### PR TITLE
Basic configuration for JS code consistency + modern JS syntax

### PR DESCRIPTION
**Pull request by davidbgk**
Using PrettierJS and an opinionated configuration (mainly: no semi, two-spaces indent) + lebab for modern JS syntax.

### CODE REVIEW

**Comment by yohanboniface** [comment]
Very cool! Let's release and then embrace the future ? :)

**Comment by davidbgk** [comment]
@yohanboniface do I run the scripts on all JS files of the repository, I just checked and there are no open PR that should be problematic to merge? 🤔

**Comment by davidbgk** [comment]
It's time to test that branch as much as we can!

**Comment by davidbgk** [comment]
Plan after discussion with @yohanboniface : we will prettier-ify the whole JS codebase (new incoming PR) and then apply lebab's transformations one-by-one (each with a dedicated PR).

**Pull request closed without merging**
