### PR TITLE
feat: add browser tabs submenu

### PR DESCRIPTION
**Pull request by yohanboniface**

### CODE REVIEW

**Comment by yohanboniface** [comment]
@Aurelie-Jallut I'm working on adding the "tabs style" menu in the browser/facets/about panels.

My first try is to factorize the code with the tabs we made for the icons, which looks like this:

image

So here is the result for the browser:

Screenshot from 2024-04-25 10-34-21

When no filter/facet is active, it looks like this:

image

Thoughts ? :)

**Comment by Aurelie-Jallut** [comment]
something like that : 
image
 
or like this : 
image

**Comment by Aurelie-Jallut** [comment]
image

**Comment by yohanboniface** [comment]
image

**Comment by Aurelie-Jallut** [comment]
@yohanboniface few feedbacks in french

**Comment by pfbreton-perso** [comment]
Wow, this is a huge improvement!  thanks for making this happen!

**Pull request merged**
