### PR TITLE
Better changelog rendering

### PR DESCRIPTION
**Pull request by davidbgk**
Before:

Capture d’écran, le 2023-12-06 à 12 46 54

After:

Capture d’écran, le 2023-12-06 à 12 47 00

### CODE REVIEW

**Comment by davidbgk** [comment]
Documentation: https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/

**Comment by yohanboniface** [comment]
Can it be even more magical ? :)

I mean, those full links are those coming from a copy-paste from the autogenerated changelog in Github, could it be that magic link or something else would display them in the short form automagically ? Otherwise, it means we need to change those links manually, no ? Which would not be ideal :(

**Comment by davidbgk** [comment]
> I mean, those full links are those coming from a copy-paste from the autogenerated changelog in Github, could it be that magic link or something else would display them in the short form automagically ? Otherwise, it means we need to change those links manually, no ? Which would not be ideal :(

🪄 we can copy-paste the rendered HTML and it looks to work! 💖

**Comment by almet** [comment]
Looks good to me 👍

**Review by yohanboniface — APPROVED** [review]

**Pull request merged**
