### PR TITLE
Ignore editors and venv.

### PR DESCRIPTION
**Pull request by openbrian**
I need ag (silver searcher) to ignore some stuff and I want my git status to be clean.

### CODE REVIEW

**Comment by yohanboniface** [comment]
I'm ok to add this, but just curious: why not setting this in your personal global .gitignore (`~/.gitignore`) ? :)

**Comment by openbrian** [comment]
Because I didn't know there was such a thing :smile:

**Comment by openbrian** [comment]
fwiw this config is also needed

```
git config --global core.excludesFile '~/.gitignore'
```

**Comment by openbrian** [comment]
I'm now using that.  Feel free to delete this PR.

**Comment by yohanboniface** [comment]
Cool!

**Pull request closed without merging**
