### PR TITLE
Add logo for social_core.backends.keycloak.KeycloakOAuth2

### PR DESCRIPTION
**Pull request by tomamplius**

### CODE REVIEW

**Comment by davidbgk** [comment]
Hello @tomamplius,

Thanks for your contribution, I would say this is something which could be added on a per instance basis [with a custom CSS](https://docs.umap-project.org/en/stable/config/customize/). Is that something that you considered?

**Comment by tomamplius** [comment]
I just reproduced what is done for github, bitbucket and twitter

KeycloakOAuth2 work like GithubOAuth2 etc...

```
AUTHENTICATION_BACKENDS = (
    "social_core.backends.keycloak.KeycloakOAuth2",
    "social_core.backends.github.GithubOAuth2",
    "social_core.backends.bitbucket.BitbucketOAuth",
    "social_core.backends.twitter.TwitterOAuth",
    "social_core.backends.openstreetmap.OpenStreetMapOAuth",
    "django.contrib.auth.backends.ModelBackend",
)

```

**Comment by davidbgk** [comment]
I know, and I doubt that it would be a good long-term strategy to add lines of CSS for [all supported backends](https://python-social-auth.readthedocs.io/en/latest/backends/index.html#supported-backends).

**Comment by tomamplius** [comment]
I one way can be use array in setting like 

AUTHENTICATION_BACKENDS_PARAMETER = [
 { keycloak : { "image" : "https://link to  keycloak.png" , "label" : "Login with keycloak" }},
 { github : { "image" : "https://link to  github.png" , "label" : "Login with github" }},
 { keycloak : { "image" : "https://link to  openstreetmap.png" , "label" : "Login with openstreetmap" }}
]

do you agree?

**Comment by tomamplius** [comment]
Yes, no? other way?

**Comment by yohanboniface** [comment]
Let's go that way for now, and see! Thanks :)

**Pull request merged**
