### PR TITLE
Set `font-display: swap` and reduce fonts’ sizes

### PR DESCRIPTION
**Pull request by davidbgk**
Using https://www.fontsquirrel.com/tools/webfont-generator with subsets: Basic Latin, Latin-1 Sup and Latin Extended-A

Capture d’écran, le 2023-05-19 à 13 42 05

### CODE REVIEW

**Comment by yohanboniface** [comment]
Humm, but what about other alphabets (arabic, russian…) ?

**Comment by davidbgk** [comment]
If I keep all the glyphs, we are at 400Ko of fonts for everybody which is suboptimal.

Maybe we should generate a font file for western languages and then a new one for other languages using the [unicode-range](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range) property?

There is a [list of unicode blocks](https://en.wikipedia.org/wiki/Unicode_block#List_of_blocks) on Wikipedia that might help.

**Comment by yohanboniface** [comment]
> If I keep all the glyphs, we are at 400Ko of fonts for everybody which is suboptimal.

Isn't this file supposed to be cached ?

I mean, how big is the issue ? And how much time do you want to spend on fixing it ?

**Comment by davidbgk** [comment]
Closing for now in favor of https://github.com/umap-project/umap/pull/1155

**Pull request closed without merging**
