### PR TITLE
fix: correct changelog link

### PR DESCRIPTION
**Pull request by eMerzh**
Hello 👋 

Small fix and maybe you prefer that i link to this page https://umap-project.readthedocs.io/en/master/changelog/

but as it was not really up to date i chose to go for github and to link to the specific version  :) 
but i'm ready to change if you prefer

Regards

### CODE REVIEW

**Comment by davidbgk** [comment]
@eMerzh thanks a lot! I just rebuilt the docs + setup a hook to ensure we're staying up-to-date 🤞 

I would prefer to keep the link to RTD but @yohanboniface might have another opinion/idea.

**Comment by yohanboniface** [comment]
Thanks a lot!

I'd say link to the full changelog in RTD too :)

**Comment by eMerzh** [comment]
Updated, 

btw it's sad that the links in RTD aren't linkified not sure what generate the md file 🤔

**Comment by yohanboniface** [comment]
> btw it's sad that the links in RTD aren't linkified 

Absolutely!

I was actually having a look at this right now:

https://github.com/mkdocs/mkdocs/issues/1711

And thus:

https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/

:)

**Pull request merged**
