### PR TITLE
Edit header polish: move "My Dashboard" and "Help" to the right, display asterisk in dirty mode

### PR DESCRIPTION
**Pull request by yohanboniface**
image

### CODE REVIEW

**Comment by davidbgk** [comment]
I hardly visualize the limit between `Aide` and `Désactiver l'édition`, maybe a light border around the button would help? /cc @Aurelie-Jallut

**Review by davidbgk — APPROVED** [review]

**Comment by Aurelie-Jallut** [comment]
@davidbgk where can I see the rendering you're talking about ?

**Comment by davidbgk** [comment]
@Aurelie-Jallut you can see it in production now

**Comment by Aurelie-Jallut** [comment]
@davidbgk thks :) 
Can we keep the same font-size for the texts "My Dashboard" "help" "cancel all" Enregist...
equivalent to 12 px.
image

**Pull request merged**
