### PR TITLE
feat: handle multiple dataUrl parameters on map load

### PR DESCRIPTION
**Pull request by davidbgk**

### CODE REVIEW

**Review by yohanboniface — APPROVED** [review]
Sounds good, but given all other parameters are unique, in particular `dataFormat` (but `color`, `labelKey` or `popupShape` too), I feel it's a bit asymmetrical. But let's see how it will be used!

**Comment by davidbgk** [comment]
I added users' documentation related to that topic:
Capture d’écran, le 2024-06-26 à 13 40 50

Capture d’écran, le 2024-06-26 à 13 41 03

**Comment by yohanboniface** [comment]
Cool! Do we also mention the `data` parameter ?

**Comment by davidbgk** [comment]
https://media3.giphy.com/media/rvaQRHCzisFeo/giphy.mp4#height=182&width=293&isvideo=true

**Pull request merged**
