### PR TITLE
#3 - create data download url

### PR DESCRIPTION
**Pull request by vostelmakh**

### CODE REVIEW

**Comment by davidbgk** [comment]
Hello @vostelmakh,

Can you provide just the commit you want to propose with an explicit title and a description clarifying the intent?

**Comment by vostelmakh** [comment]
> Hello @vostelmakh,
> 
> Can you provide just the commit you want to propose with an explicit title and a description clarifying the intent?
Hello @davidbgk 
I wanted to create commit to fork https://github.com/CraftCoderr/umap , but created it to main repository.
I'll close this PR.

**Comment by yohanboniface** [comment]
@vostelmakh just curious: are you planning to propose some of your work on this main repo at some point ?

**Comment by CraftCoderr** [comment]
Hello @yohanboniface,
We need extra functionality on umap like what described in #584 but with certain feature - to give ability for third-party users to propose changes on public map and ability for owner and admins to accept these propositions.
If we succeed, we will try to create a PR here.

**Pull request closed without merging**
