### PR TITLE
fix: encode the whole url parameter for OEmbed

### PR DESCRIPTION
**Pull request by davidbgk**
See https://github.com/umap-project/umap/pull/1526#issuecomment-1937040472

I'm not fully sure it'll fix the issue though.

### CODE REVIEW

**Comment by yohanboniface** [comment]
Do we still need the quoting fix ?

**Comment by davidbgk** [comment]
> Do we still need the quoting fix ?

I guess it might help some implementations 👍

**Review by yohanboniface — APPROVED** [review]

**Comment by bristow** [comment]
I don't know if this fix is online, but unfortunately it still doesn't work. Damn!

**Comment by davidbgk** [comment]
Grr, I'm starting to question the client now 😅 Do you know where is the code of the plugin you are using?

**Comment by bristow** [comment]
if you don't believe me ;) check out this site: https://debug.iframely.com/ ;)

An OSM map will work: https://www.openstreetmap.org/?mlat=43.7473&mlon=1.2881#map=9/43.7473/1.2881

But an umap doesn't: https://umap.openstreetmap.fr/fr/map/lycees-martiniere-diderot_167175

**Comment by davidbgk** [comment]
> if you don't believe me ;)

well, that's not exactly what I said :)

Thanks for the debugging tool and that's where we need to define what `work` means.

https://debug.iframely.com/?uri=https%3A%2F%2Fwww.openstreetmap.org%2F%3Fmlat%3D43.7473%26mlon%3D1.2881%23map%3D9%2F43.7473%2F1.2881 doesn't have any data related to oembed

https://debug.iframely.com/?uri=https%3A%2F%2Fumap.openstreetmap.fr%2Ffr%2Fmap%2Flycees-martiniere-diderot_167175 does have that data though (`Other meta` tab)

Reading the code of the OSM source page, I can't see any discoverable address for oEmbed.

uMap's oEmbed address does return the correct JSON: https://umap.openstreetmap.fr/map/oembed/?url=https%3A%2F%2Fumap.openstreetmap.fr%2Ffr%2Fmap%2Flycees-martiniere-diderot_167175&format=json with the corresponding HTML iframe code.

Are you sure your website is actually using the oEmbed format?

**Pull request merged**
