### PR TITLE
Check both matching pk and slug for map urls

### PR DESCRIPTION
**Pull request by davidbgk**
Note: this is some kind of breaking change if previous URLs have incorrect (but still working) slugs.

Also, the URL change when changing the title and now the resulting slug is significant during the matching.

PS: a clean commit is available to filter out black noise.

### CODE REVIEW

**Comment by yohanboniface** [comment]
I'm not sure to see how this answers the #905 : if we still support the pk, then we still have the issue, or I'm missing something ?

**Comment by davidbgk** [comment]
> I'm not sure to see how this answers the #905 : if we still support the pk, then we still have the issue, or I'm missing something ?

With the `query_pk_and_slug` option, the check will be performed on both the `pk` _and_ the `slug` so you cannot guess the URL from the incremental `pk` only.

**Comment by yohanboniface** [comment]
:+1:

**Comment by davidbgk** [comment]
I'm closing it as we will not solve that issue with that strategy. We plan to define a proper UUID field on the model and use it for future maps because we have a lot of maps out there and we do not want to break the web. It's a trade-off.

Amongst the potential implementations for future devs, there is a view that would check if a UUID is available for a given map and deal with it from the URL (instead of current id) or return a 404. But if there is no UUID for that legacy map, in that case fallback to the ancient access of the map, with id, to maintain maps' URLs working.

**Pull request closed without merging**
